### ISSUE TITLE
Add "demo" qualifier to interesting tests

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/ios-demo-app#3]
![image](https://user-images.githubusercontent.com/3640206/77952806-394b7d00-729a-11ea-915f-0e0af481c805.png)

Such that I can filter by "demo" and see the 1-5 tests that are worth highlighting in this app.

Also, add an identifier to "dummy" tests. As such, this project would have:

- a very limited amount of "demo" tests (1-5)
- a lot of "dummy" tests (~1000s)
- any other test that may not be dummy tests, but still not interesting enough to be highlighted as "demo"

**Comment by nachoBonafonte** [comment]
Done
