### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by borjaburgos** [scope-demo-app/ios-demo-app#4]
README should contain instructions on how to clone this project and how to run it locally with Scope for Mac/Windows to obtain Scratchpad results.

Ideally, all integration tests are automatically configured to be ran against our "production" hamburguesía instance, such that when I run them locally I still the full traces in Scratchpad.

Make sure README includes the SCOPE Badge.

**Comment by borjaburgos** [comment]
Also include instructions for manual testing

**Comment by nachoBonafonte** [comment]
Done
